# Generated by Django 5.2 on 2025-04-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordering_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
