# Generated by Django 5.2 on 2025-07-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('pm', 'Project Management'), ('dev', 'Development')], default='dev', max_length=10),
        ),
    ]
