# Generated by Django 5.2 on 2025-07-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_skill_staticsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticSection',
        ),
    ]
